#!/usr/bin/env python3
"""M34 second-category transfer test of the frozen M30 detector."""
from __future__ import annotations

import argparse
import json
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
import action_executor as EXEC  # noqa: E402
from hf_telemetry_backend import HFTelemetryBackend  # noqa: E402
import m23_within_model as M23  # noqa: E402
import m26_objective_error as M26  # noqa: E402
import m28_ablation_calibration as M28  # noqa: E402
import m29_scaled_error_power as M29  # noqa: E402
import m30_decisive_increment as M30  # noqa: E402
import m31_intervention_study as M31  # noqa: E402
import m32_structured_repair as M32  # noqa: E402
import m33_tool_routing as M33  # noqa: E402
import verifiers as VZ  # noqa: E402

POLICIES = M33.POLICIES
CAPTURE_DIR = "m34_qwen15_moe"


def load_manifest(path):
    manifest = json.loads(Path(path).read_text())
    if manifest.get("selection_status") != \
            "predeclared_before_m34_task_generation":
        raise ValueError("M34 manifest is not predeclared before generation")
    bands = manifest.get("bands") or []
    tasks = manifest.get("tasks") or []
    if manifest.get("n_tasks") != 384 or len(tasks) != 384 or len(bands) != 6:
        raise ValueError("M34 manifest must declare six bands and 384 tasks")
    if len({task["task_id"] for task in tasks}) != 384:
        raise ValueError("M34 task ids must be unique")
    counts = Counter(task["band"] for task in tasks)
    for band in bands:
        if band.get("n_tasks") != 64 or counts[band["band_id"]] != 64:
            raise ValueError(f"M34 band size mismatch: {band['band_id']}")
    if manifest["frozen_trigger"].get("threshold_fail_probability") != 0.5:
        raise ValueError("M34 frozen trigger threshold changed")
    if tuple(sorted(manifest["policies"])) != tuple(sorted(POLICIES)):
        raise ValueError("M34 policy set changed")
    if manifest["generation"].get("additive_term_range") != [2, 99]:
        raise ValueError("M34 additive term range changed")
    return manifest


def prior_tuples_through_m33(m29_path, m30_path, m31_path, m32_path,
                             m33_path):
    """Every (a, b) tuple generated by the M29-M33 manifests."""
    prior = M33.prior_tuples_through_m32(m29_path, m30_path, m31_path,
                                         m32_path)
    m33_manifest = M33.load_manifest(m33_path)
    seed = m33_manifest["generation"]["seed"]
    for band in m33_manifest["bands"]:
        rng = random.Random(f"{seed}:{band['band_id']}")
        seen = set(prior[band["band_id"]])
        tuples = M30._draw_tuples(rng, band, band["n_tasks"], seen)
        prior[band["band_id"]] |= set(tuples)
    return prior


def generate_tasks(manifest, m29_path, m30_path, m31_path, m32_path,
                   m33_path):
    seed = manifest["generation"]["seed"]
    template = manifest["prompt_template"]
    c_low, c_high = manifest["generation"]["additive_term_range"]
    prior = prior_tuples_through_m33(m29_path, m30_path, m31_path, m32_path,
                                     m33_path)
    slots = defaultdict(list)
    for task in manifest["tasks"]:
        slots[task["band"]].append(task)
    tasks = []
    for band in manifest["bands"]:
        band_id = band["band_id"]
        rng = random.Random(f"{seed}:{band_id}")
        seen = set(prior[band_id])
        tuples = M30._draw_tuples(rng, band, band["n_tasks"], seen)
        for slot, (a, b) in zip(slots[band_id], tuples):
            c = rng.randint(c_low, c_high)
            tasks.append({
                "prompt_id": slot["task_id"],
                "m34_band": band_id,
                "task_category": "math",
                "a": a, "b": b, "c": c,
                "expression": f"{a}*{b}+{c}",
                "known_answer": str(a * b + c),
                "prompt": template.format(a=a, b=b, c=c),
            })
    if len(tasks) != 384 or len({t["prompt_id"] for t in tasks}) != 384:
        raise ValueError("M34 generation did not produce 384 unique tasks")
    order = {task["task_id"]: index
             for index, task in enumerate(manifest["tasks"])}
    tasks.sort(key=lambda task: order[task["prompt_id"]])
    return tasks


def prepare_private_tasks(manifest_path, m29_path, m30_path, m31_path,
                          m32_path, m33_path, output_path):
    manifest = load_manifest(manifest_path)
    tasks = generate_tasks(manifest, m29_path, m30_path, m31_path, m32_path,
                           m33_path)
    out = Path(output_path); out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(json.dumps(task) + "\n" for task in tasks))
    return manifest, tasks


def tool_answer(task):
    """Deterministic integer evaluator over the predeclared expression."""
    a, b, c = task["a"], task["b"], task["c"]
    assert task["expression"] == f"{a}*{b}+{c}"
    return str(a * b + c)


def run_captures(manifest, tasks, model_ref, captures_root):
    """Single-model-load greedy originals capture (only M34 GPU phase)."""
    import capture_router_logits as CAP
    import torch

    args = argparse.Namespace(
        model=model_ref, dtype="bf16", device_map="auto",
        max_gpu_mem_gib=20.0, trust_remote_code=False)
    tok, model, cfg = CAP.load_model(args)
    root = Path(captures_root)
    cap_tokens = manifest["decode_protocols"]["original"]["decode_cap_tokens"]
    print(f"[jlens] M34 originals capture ({len(tasks)})", flush=True)
    for task in tasks:
        dest = root / CAPTURE_DIR / f"{task['prompt_id']}.pt"
        if CAP._valid_capture(dest):
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        input_ids, router, hidden, steps = CAP.capture_one(
            tok, model, task["prompt"], 4096, max_new_tokens=cap_tokens,
            router_only=True, chat_template=True)
        torch.save({
            "prompt_id": task["prompt_id"], "input_ids": input_ids,
            "router_logits": router, "hidden_states": hidden,
            "model_type": cfg.model_type, "model_path": str(model_ref),
            "decode_steps": steps,
            "generated_output": tok.decode(
                [s["generated_token_id"] for s in steps],
                skip_special_tokens=True)}, dest)
    print("[jlens] M34 captures complete", flush=True)


def evaluate(manifest, rows):
    """rows: per-task dicts with band, p_fail, original_pass, tool_pass."""
    threshold = manifest["frozen_trigger"]["threshold_fail_probability"]
    n = len(rows)
    triggered = {row["task_id"] for row in rows if row["p_fail"] >= threshold}
    fails = {row["task_id"] for row in rows if not row["original_pass"]}
    rng = random.Random("m34:random-trigger")
    random_set = set(rng.sample(sorted(row["task_id"] for row in rows),
                                len(triggered)))
    attempted_by_policy = {
        "no_repair": set(),
        "tool_on_every_task": {row["task_id"] for row in rows},
        "random_trigger_tool": random_set,
        "telemetry_trigger_tool": triggered,
    }

    success, metrics = {}, {}
    for policy, attempted in attempted_by_policy.items():
        outcomes, invocations = [], 0
        rescued = false_alarms = 0
        for row in rows:
            final_pass = row["original_pass"]
            if row["task_id"] in attempted:
                invocations += 1
                if final_pass:
                    false_alarms += 1
                elif row["tool_pass"]:
                    final_pass = True
                    rescued += 1
            outcomes.append(1 if final_pass else 0)
        success[policy] = outcomes
        metrics[policy] = {
            "verified_success_rate": sum(outcomes) / n,
            "tool_invocations": invocations,
            "candidate_decode_tokens": 0,
            "errors_rescued": rescued,
            "errors_introduced": 0,
            "false_alarm_checks": false_alarms,
        }
        original_success = [1 if row["original_pass"] else 0 for row in rows]
        if any(o < s for o, s in zip(outcomes, original_success)):
            raise ValueError("M34 stop: a policy replaced a passing original")

    trigger_hits = len(triggered & fails)
    precision = trigger_hits / len(triggered) if triggered else None
    recall = trigger_hits / len(fails) if fails else None

    h1_cfg = manifest["hypotheses"]["h1_routing_usefulness"]
    h1 = {}
    for name_a, name_b in h1_cfg["comparisons"]:
        interval = M32._success_delta_bootstrap(
            success[name_a], success[name_b],
            f"{h1_cfg['bootstrap_seed_prefix']}:{name_a}-vs-{name_b}",
            iterations=h1_cfg["bootstrap_iterations"])
        h1[f"{name_a}_vs_{name_b}"] = {
            "delta_success_rate": (
                metrics[name_a]["verified_success_rate"]
                - metrics[name_b]["verified_success_rate"]),
            "delta_success_bootstrap_95pct": interval,
        }
    intervals = [entry["delta_success_bootstrap_95pct"]
                 for entry in h1.values()]
    if all(low > 0 for low, _ in intervals):
        h1_verdict = "useful"
    elif any(high < 0 for _, high in intervals):
        h1_verdict = "harmful"
    else:
        h1_verdict = "not_established"

    h2_cfg = manifest["hypotheses"]["h2_routing_efficiency"]
    none_rate = metrics["no_repair"]["verified_success_rate"]
    tool_rate = metrics["tool_on_every_task"]["verified_success_rate"]
    tel_rate = metrics["telemetry_trigger_tool"]["verified_success_rate"]
    full_uplift = tool_rate - none_rate
    retention = ((tel_rate - none_rate) / full_uplift) if full_uplift else None
    invocation_fraction = metrics["telemetry_trigger_tool"][
        "tool_invocations"] / n
    boot_rng = random.Random(h2_cfg["retention_bootstrap_seed"])
    retention_samples = []
    for _ in range(h2_cfg["bootstrap_iterations"]):
        indices = [boot_rng.randrange(n) for _ in range(n)]
        none_s = sum(success["no_repair"][i] for i in indices)
        tool_s = sum(success["tool_on_every_task"][i] for i in indices)
        tel_s = sum(success["telemetry_trigger_tool"][i] for i in indices)
        if tool_s > none_s:
            retention_samples.append((tel_s - none_s) / (tool_s - none_s))
    retention_samples.sort()
    retention_interval = ([
        retention_samples[int(0.025 * (len(retention_samples) - 1))],
        retention_samples[int(0.975 * (len(retention_samples) - 1))]]
        if retention_samples else None)
    h2_verdict = ("efficient"
                  if retention is not None and retention >= 0.80
                  and invocation_fraction <= 0.60
                  else "not_established")

    maintained = (precision is not None and recall is not None
                  and precision >= 0.80 and recall >= 0.75)
    if maintained:
        t1_verdict = "transfer_maintained"
    elif h1_verdict == "useful":
        t1_verdict = "transfer_degraded"
    else:
        t1_verdict = "transfer_failed"

    per_band = defaultdict(lambda: {
        "n_tasks": 0, "original_fail_count": 0, "trigger_count": 0,
        "trigger_true_positives": 0, "telemetry_rescues": 0})
    for row in rows:
        b = per_band[row["band"]]
        b["n_tasks"] += 1
        fail = not row["original_pass"]
        trig = row["p_fail"] >= threshold
        b["original_fail_count"] += fail
        b["trigger_count"] += trig
        b["trigger_true_positives"] += trig and fail
        b["telemetry_rescues"] += trig and fail and row["tool_pass"]
    band_rows = []
    for band in sorted(per_band):
        b = per_band[band]
        band_rows.append({
            "band": band, **b,
            "trigger_precision": (b["trigger_true_positives"]
                                  / b["trigger_count"])
            if b["trigger_count"] else None,
            "trigger_recall": (b["trigger_true_positives"]
                               / b["original_fail_count"])
            if b["original_fail_count"] else None,
        })

    return {
        "schema_version": 1,
        "run_kind": "m34_detector_transfer_evaluation",
        "task_category": manifest["task_category"],
        "n_rows_evaluated": n,
        "frozen_trigger": {
            "source": "M30 full_telemetry (refit-verified)",
            "threshold_fail_probability": threshold,
            "trigger_count": len(triggered),
            "trigger_rate": len(triggered) / n,
            "trigger_precision": precision,
            "trigger_recall": recall,
        },
        "original_label_distribution": {
            "pass": n - len(fails), "fail": len(fails)},
        "t1_transfer_classification": {
            "thresholds": manifest["transfer_classification"],
            "verdict": t1_verdict,
        },
        "policy_metrics": metrics,
        "h1_routing_usefulness": {
            "comparisons": h1, "verdict": h1_verdict},
        "h2_routing_efficiency": {
            "uplift_retention": retention,
            "uplift_retention_bootstrap_95pct": retention_interval,
            "invocation_fraction": invocation_fraction,
            "invocations_saved_vs_tool_on_every_task": (
                metrics["tool_on_every_task"]["tool_invocations"]
                - metrics["telemetry_trigger_tool"]["tool_invocations"]),
            "verdict": h2_verdict,
        },
        "per_band_descriptives_secondary": {
            "confirmatory": False, "bands": band_rows},
        "claim_rules": manifest["hypotheses"],
        "framing": manifest["framing"],
        "per_task_predictions_persisted_publicly": False,
        "candidate_only": True,
        "production_gated": True,
        "privacy_check_status":
            "aggregate metrics/intervals only; no ids/text/paths",
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--manifest",
                    default="data/prompts/m34_transfer_manifest.json")
    ap.add_argument("--m29-manifest",
                    default="data/prompts/m29_power_manifest.json")
    ap.add_argument("--m30-manifest",
                    default="data/prompts/m30_decisive_manifest.json")
    ap.add_argument("--m31-manifest",
                    default="data/prompts/m31_intervention_manifest.json")
    ap.add_argument("--m32-manifest",
                    default="data/prompts/m32_repair_manifest.json")
    ap.add_argument("--m33-manifest",
                    default="data/prompts/m33_tool_routing_manifest.json")
    ap.add_argument("--m30-labels",
                    default="reports/shadow/private/m30_error_labels_local.jsonl")
    ap.add_argument("--m30-telemetry",
                    default="reports/shadow/private/"
                            "m30_hf_telemetry_records_local.jsonl")
    ap.add_argument("--m30-evaluation",
                    default="reports/telemetry/"
                            "hf_m30_decisive_increment_evaluation.json")
    ap.add_argument("--tasks-out",
                    default="reports/shadow/private/m34_hf_prompts_local.jsonl")
    ap.add_argument("--captures-root", default="data/captures")
    ap.add_argument("--model-ref")
    ap.add_argument("--prepare-only", action="store_true")
    ap.add_argument("--capture", action="store_true")
    ap.add_argument("--telemetry-out",
                    default="reports/shadow/private/"
                            "m34_hf_telemetry_records_local.jsonl")
    ap.add_argument("--rows-out",
                    default="reports/shadow/private/m34_transfer_rows_local.jsonl")
    ap.add_argument("--summary-out",
                    default="reports/telemetry/hf_m34_transfer_run_summary.json")
    ap.add_argument("--evaluation-out",
                    default="reports/telemetry/hf_m34_transfer_evaluation.json")
    args = ap.parse_args(argv)

    manifest, tasks = prepare_private_tasks(
        args.manifest, args.m29_manifest, args.m30_manifest,
        args.m31_manifest, args.m32_manifest, args.m33_manifest,
        args.tasks_out)
    root = Path(args.captures_root)
    if args.prepare_only:
        done = sum((root / CAPTURE_DIR / f"{t['prompt_id']}.pt").exists()
                   for t in tasks)
        print(f"[jlens] M34 predeclared tasks: {len(tasks)}; "
              f"original captures existing={done}")
        return 0
    if not args.model_ref:
        raise ValueError("--model-ref is required")
    if args.capture:
        run_captures(manifest, tasks, args.model_ref, args.captures_root)
        return 0

    classifier = M31.frozen_m30_classifier(
        args.m30_manifest, args.m30_labels, args.m30_telemetry,
        args.m30_evaluation)

    import torch
    from jsonschema import Draft7Validator
    telemetry_schema = Draft7Validator(json.loads(Path(
        "schema/hf_telemetry_record_v1.json").read_text()))
    backend = HFTelemetryBackend(
        model_ref=args.model_ref, source_kind="local_path", top_k=5)
    adapter = EXEC.FixtureRetrievalAdapter({
        "*": {"source_kind": "public_fixture",
              "context": "M34 controlled local fixture context",
              "confidence": 0.8}})
    cfg = M23._qwen_config()
    bands_manifest = {"bands": manifest["bands"]}

    telemetry_rows, rows = [], []
    undecided = Counter()
    original_capped = 0
    for task in tasks:
        path = root / CAPTURE_DIR / f"{task['prompt_id']}.pt"
        if not path.exists():
            raise FileNotFoundError(f"missing M34 capture: {task['prompt_id']}")
        original = torch.load(path, map_location="cpu", weights_only=False)
        telemetry, _runtime, action, result = M23.process_same_capture(
            task, original, backend, cfg=cfg, retrieval_adapter=adapter)
        errors = list(telemetry_schema.iter_errors(telemetry))
        if errors:
            raise ValueError(
                f"invalid telemetry for {task['prompt_id']}: "
                f"{errors[0].message}")
        if action["action_type"] != "checker_needed":
            raise ValueError(
                f"M34 action drift: {task['prompt_id']} -> "
                f"{action['action_type']}")
        telemetry_rows.append(telemetry)
        original_capped += telemetry["decode_step_count"] == 64
        original_verdict = M26.label_from_result(result)
        if original_verdict == "undecided":
            undecided["original"] += 1
            continue
        label_row = {"task_id": task["prompt_id"], "band": task["m34_band"]}
        features = M29.feature_row(bands_manifest, label_row, telemetry)
        p_fail = M28.fail_probability(classifier, features)
        tool_verdict = M32.verdict_for(tool_answer(task), task)
        rows.append({
            "task_id": task["prompt_id"], "band": task["m34_band"],
            "p_fail": p_fail,
            "original_pass": original_verdict == "pass",
            "tool_pass": tool_verdict == "pass",
        })

    Path(args.telemetry_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.telemetry_out).write_text(
        "".join(json.dumps(row) + "\n" for row in telemetry_rows))
    Path(args.rows_out).write_text(
        "".join(json.dumps(row) + "\n" for row in rows))

    evaluation = evaluate(manifest, rows)
    Path(args.evaluation_out).write_text(
        json.dumps(evaluation, indent=1) + "\n")
    summary = {
        "schema_version": 1,
        "run_kind": "m34_detector_transfer_dataset",
        "task_category": manifest["task_category"],
        "n_tasks": len(tasks),
        "n_rows_evaluated": len(rows),
        "undecided_excluded_counts": dict(undecided),
        "original_decode_cap_reached_count": original_capped,
        "capture_phase_counts": {
            "original": sum((root / CAPTURE_DIR / f"{t['prompt_id']}.pt")
                            .exists() for t in tasks)},
        "operands_disjoint_from_m29_through_m33": True,
        "no_posthoc_selection": True,
        "per_task_labels_or_predictions_persisted_publicly": False,
        "raw_text_token_tensor_or_path_persisted_publicly": False,
        "candidate_only": True,
        "production_gated": True,
        "privacy_check_status": "aggregate-only detector transfer summary",
    }
    Path(args.summary_out).write_text(json.dumps(summary, indent=1) + "\n")
    trig = evaluation["frozen_trigger"]
    print(f"[jlens] M34: {len(rows)} rows; "
          f"T1={evaluation['t1_transfer_classification']['verdict']} "
          f"(precision={trig['trigger_precision']} "
          f"recall={trig['trigger_recall']}); "
          f"H1={evaluation['h1_routing_usefulness']['verdict']}; "
          f"H2={evaluation['h2_routing_efficiency']['verdict']}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
